server:
  servlet:
    context-path: /api/transporte
  port: 8084

key:
  pub: ENC(4ueq6bRoICGnEHFzntpKa6w24jXNa+ON9USwcYYKsBCOIiEpK3UFNIq52d6CWDtPSSGsIpDrlfU=)
  prv: TEST

jasypt:
  encryptor:
    password: ${JASYPTKEY}
    algorithm: PBEWithMD5AndDES

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${CONEXIONBD}
    username: ${USERBD}
    password: ${PASSWORD}

  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/data