CREATE TABLE IF NOT EXISTS TRANSPORTE_SANDBOX.CONDUCTORES(
ID INT NOT NULL AUTO_INCREMENT,
PRIMER_NOMBRE VARCHAR(50) NOT NULL,
SEGUNDO_NOMBRE VARCHAR(50),
PRIMER_APELLIDO VARCHAR(50) NOT NULL,
SEGUNDO_APELLIDO VARCHAR(50),
NUMERO_IDENTIFICACION INT NOT NULL,
PRIMARY KEY (ID));


CREATE TABLE IF NOT EXISTS TRANSPORTE_SANDBOX.VIAJES(
ID INT NOT NULL AUTO_INCREMENT,
LATITUD_INICIO DOUBLE DEFAULT 0,
LONGITUD_INICIO DOUBLE DEFAULT 0,
LATITUD_FIN DOUBLE DEFAULT 0,
LONGITUD_FIN DOUBLE DEFAULT 0,
EMAIL_CLIENTE VARCHAR(50) NOT NULL,
ID_CONDUCTOR INT NOT NULL,
foreign key (ID_CONDUCTOR) references TRANSPORTE_SANDBOX.CONDUCTORES (ID),
ESTADO VARCHAR(50) DEFAULT 'EN_PROCESO',
MONTO DOUBLE DEFAULT 0,
PRIMARY KEY (ID));